spring.application.name=shrnkit

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shrnkit_db
spring.datasource.username=shrnkit_user
spring.datasource.password=shrnkit_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.data.redis.host=localhost
spring.data.redis.port=6379

# jwt
jwt.secret=EyqyWCOggbE2yLsHjFj9o5r+UAASuNJNbqIIUOImIcI=
jwt.access-token-expiration=900000
refresh.token-expiration=604800000